esphome:
  name: pelletkachel

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  

            
ota:
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pelletstove Fallback Hotspot"
    password: "xxxxxxxxxxxxxx"

captive_portal:
    
switch:
  - platform: gpio
    pin: 14
    name: "A"
    id: pellet_A
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: pellet_A

  - platform: gpio
    pin: 12
    name: "Up"
    id: pellet_UP
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: pellet_UP
    
  - platform: gpio
    pin: 13
    name: "On/Off"
    id: pellet_ONOFF
    on_turn_on:
    - delay: 3000ms
    - switch.turn_off: pellet_ONOFF
    
  - platform: gpio
    pin: 5
    name: "Down"
    id: pellet_DOWN
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: pellet_DOWN
