esphome:
  name: pelletkachel

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  

            
ota:
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pelletstove Fallback Hotspot"
    password: "xxxxxxxxxxxxxx"

captive_portal:
    
switch:
  - platform: gpio
    pin: 2
    name: "A"
